config/routes.rb
Rails.application.routes.draw do
  root 'schedules#index'
  post "schedules/new",to:"schedules#create"
  delete "schedules/:id",to:"schedules#destroy"
  resources :schedules
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end
  
  def new
    @schedules = Schedule.new
  end
  
  def create
    @schedule = Schedule.new(params.permit(:title, :startdate, :enddate, :allday, :introduction))
    if @schedule.save
      flash[:notice] ="ユーザーを新規登録しました"
      redirect_to root_path
    else
      render "new"
    end
  end 
  
  def show
    @schedule = Schedule.find(params[:id])
  end 
  
  def edit
    @schedule = Schedule.find(params[:id])
  end 
  
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :startdate, :enddate, :allday, :introduction, :updated_at))
      flash[:notice] ="スケジュールの情報を更新しました"
      redirect_to root_path
    else
      render "edit"
    end
  end 
  
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] ="スケジュールを削除しました"
    redirect_to :schedules,status: :see_other
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
    <footer>
      <h1>
      現在の日付<%= Date.current.strftime('%Y年 %m月 %d日') %>
      <%= if current_page?(root_path)
             "残りのタスク数は#{@schedules.length}個です"
          end  %>
      </h1>
    </footer>
  </body>
</html>

app/views/schedules/edit.html.erb
<h3>ユーザー編集</h3>

    <%= form_with model: @schedule do |f| %>
      <table>
        <tr>
          <th><%= f.label :title ,"タイトル" %></th>
          <td><%= f.text_field :title %></td>
        </tr>

        <tr>
          <th><%= f.label :startdate ,"開始日" %></th>
          <td><%= f.date_field :startdate %></td>
        </tr>

        <tr>
          <th><%= f.label :enddate ,"終了日" %></th>
          <td><%= f.date_field :enddate %></td>
        </tr>

        <tr>
          <th><%= f.label :allday ,"終日" %></th>
          <td><%= f.check_box :allday %></td>
        </tr>

        <tr>
          <th><%= f.label :introduction ,"スケジュールメモ" %></th>
          <td><%= f.text_area :introduction %></td>
        </tr>
      </table>

      <div>
        <ul>
          <li><%= f.submit "更新を完了する"%></li>
          <li><%= link_to "ユーザー情報一覧に戻る", root_path %></li>
        </ul>
      </div>
    <% end %>

app/views/schedules/index.html.erb
<h3>スケジュール一覧</h3>

<% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
<% end %>
 
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>タイトル</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>終日</th>
          <th>スケジュール更新日時</th>
          <th>確認</th>
          <th>編集</th>
          <th>削除</th>
        </tr>
      </thead>
 
      <tbody>
        <% @schedules.each do |schedule| %>
          <tr>
            <td><%= schedule.id %></td>
            <td><%= schedule.title %></td>
            <td><%= schedule.startdate.to_fs(:datetime_jp) %></td>
            <td><%= schedule.enddate.to_fs(:datetime_jp) %></td>
            <td><%=if schedule.allday == true
                  "◯"
                else
                  "×"
                end  %>
            </td>
            <td><%= schedule.updated_at.to_fs(:datetime_jp) %></td>
            <td>
            <%= link_to "参照",schedule %>
            </td>
            <td>
            <%= link_to "編集", [:edit,schedule] %>
            </td>
            <td>
            <%= link_to "削除",schedule,data: {turbo_method: :delete}, turbo_confirm: "本当に削除しますか？" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
 
    <p><%= link_to "ユーザー新規登録", :new_schedule %></p>

app/views/schedules/new.html.erb
<h3>ユーザー新規作成</h3>
 
    <%= form_with model: @schedule do |f| %>
      <table>
        <tr>
          <th><%= f.label :title ,"タイトル" %></th>
          <td><%= f.text_field :title %></td>
        </tr>
 
        <tr>
          <th><%= f.label :startdate ,"開始日" %></th>
          <td><%= f.date_field :startdate %></td>
        </tr>
 
        <tr>
          <th><%= f.label :enddate ,"終了日" %></th>
          <td><%= f.date_field :enddate %></td>
        </tr>
 
        <tr>
          <th><%= f.label :allday ,"終日" %></th>
          <td><%= f.check_box :allday %></td>
        </tr>
        
        <tr>
          <th><%= f.label :introduction ,"スケジュールメモ" %></th>
          <td><%= f.text_area :introduction %></td>
        </tr>
      </table>
 
      <div>
        <ul>
          <li><%= f.submit "登録完了する"%></li>
          <li><%= link_to "ユーザー情報一覧に戻る", :schedules %></li>
        </ul>
      </div>
    <% end %>
    

app/views/schedules/show.html.erb
<h3>ユーザー詳細</h3>

    <table>    
      <tr>
        <th>タイトル</th>
        <td><%= @schedule.title %></td>
      </tr>
      <tr>
        <th>開始日</th>
        <td><%= @schedule.startdate.to_fs(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>終了日</th>
        <td><%= @schedule.enddate.to_fs(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>終日</th>
        <td><%= @schedule.allday %></td>
      </tr>
      <tr>
        <th>スケジュールメモ</th>
        <td><%= @schedule.introduction %></td>
      </tr>
    </table>

    <div>
      <ul>
        <li><%= link_to "ユーザー情報一覧に戻る", root_path %></li>
      </ul>
      <ul>
        <li><%= link_to "スケジュールを編集する", edit_schedule_url %></li>
      </ul>
    </div>